# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Andrew McPherson
tagline:          'Computing Science PhD'
description:      'Computing Science PhD'
url:              http://amcpherson.gihub.io
baseurl:          /

